Repository wecode-bootcamp-korea/17-2nd-WantUs-backend, pull requests merged in 2021-03, with the labels that each got.

#1 [17기 장성준] models.py 리뷰 수정 완료
  apply/__init__.py
  apply/admin.py
  apply/apps.py
  apply/migrations/0001_initial.py
  apply/migrations/0002_auto_20210303_1856.py
  apply/migrations/__init__.py
  apply/models.py
  apply/tests.py
  apply/views.py
  posting/__init__.py
  posting/admin.py
  posting/apps.py
  posting/migrations/0001_initial.py
  posting/migrations/0002_auto_20210303_1856.py
  posting/migrations/0003_auto_20210304_1547.py
  posting/migrations/0004_auto_20210304_1816.py
  posting/migrations/__init__.py
  posting/models.py
  posting/tests.py
  posting/views.py
  resume/__init__.py
  resume/admin.py
  resume/apps.py
  resume/migrations/0001_initial.py
  resume/migrations/0002_auto_20210304_1547.py
  resume/migrations/__init__.py
  resume/models.py
  resume/tests.py
  resume/views.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210303_1909.py
  user/migrations/0003_auto_20210304_1547.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
  wantus/settings.py
Labels: Status: Accepted

#5 [17기 장성준] models.py 수정
  apply/migrations/0001_initial.py
  apply/migrations/0002_auto_20210305_1352.py
  posting/migrations/0001_initial.py
  posting/migrations/0002_auto_20210305_1352.py
  posting/migrations/0003_auto_20210304_1547.py
  posting/migrations/0004_auto_20210304_1816.py
  posting/models.py
  resume/migrations/0001_initial.py
  resume/migrations/0002_auto_20210304_1547.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210303_1909.py
  user/migrations/0003_auto_20210304_1547.py
Labels: Status: 리뷰 요청

#3 [17기 장성준] login-decorator 작성 완료, unittest -> (다른 view에서 확인했습니다!)
  utils.py
Labels: Status: 리뷰 요청

#9 [17기 강현수] Resume models.py수정
  posting/migrations/0003_posting_work_experience.py
  posting/models.py
  resume/migrations/0002_auto_20210307_1329.py
  resume/migrations/0003_auto_20210307_1330.py
  resume/models.py
Labels: Status: 리뷰 요청

#2 [17기 장성준] SignView 작성 완료, unittest 완료(코드리뷰 반영)
  user/tests.py
  user/urls.py
  user/views.py
  wantus/urls.py
Labels: Status: Accepted

#7 [17기 강현수]: PostingDetailView GET 작성완료 및 UnitTest 완료
  posting/tests.py
  posting/urls.py
  posting/views.py
  user/models.py
  utils.py
  wantus/urls.py
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#6 [17기 김채현] 회원유저용 MainView GET 구현 및 unittest 완료 (찐)
  posting/tests.py
  posting/urls.py
  posting/views.py
  utils.py
  wantus/urls.py
Labels: Status: Accepted

#13 [17기 강현수] resume models.py uuidcode 추가
  resume/migrations/0004_resumefile_uuidcode.py
  resume/migrations/0005_auto_20210310_1019.py
  resume/migrations/0006_merge_20210310_1223.py
  resume/migrations/0007_resumefile_is_default.py
  resume/models.py
Labels: Status: Accepted

#8 [17기 강현수]Detail page 무한 스크롤 구현 완료 및 Unittest완료
  posting/tests.py
  posting/urls.py
  posting/views.py
  utils.py
Labels: Status: Accepted, Status: 리뷰 요청

#18 [17기 장성준] models 수정
  apply/migrations/0001_initial.py
  apply/migrations/0002_auto_20210310_1648.py
  apply/migrations/0003_auto_20210310_0331.py
  posting/migrations/0001_initial.py
  posting/migrations/0002_auto_20210310_1648.py
  posting/migrations/0003_posting_work_experience.py
  resume/migrations/0001_initial.py
  resume/migrations/0002_auto_20210307_1329.py
  resume/migrations/0003_auto_20210307_1330.py
  resume/migrations/0004_auto_20210310_0403.py
  resume/migrations/0004_resumefile_uuidcode.py
  resume/migrations/0005_auto_20210310_1019.py
  resume/migrations/0006_merge_20210310_1223.py
  resume/migrations/0007_resumefile_is_default.py
  resume/models.py
  user/migrations/0001_initial.py
Labels: Status: Accepted

#11 [17기 강현수] Posting bookmark, like Post View 작성 및 테스트 완료
  posting/tests.py
  posting/urls.py
  posting/views.py
  utils.py
  wantus/urls.py
Labels: Status: Accepted

#12 [17기 강현수] ResumeFileUploadView 작성 및 유닛 테스트 완료(mock file, patch 적용)
  resume/tests.py
  resume/urls.py
  resume/views.py
  utils.py
  wantus/asset_storage.py
  wantus/settings.py
  wantus/urls.py
Labels: Status: Accepted

#4 [17기 장성준] ProfileView 작성 완료, unittest 완료 (코드리뷰 반영 완료, 충돌 해결)
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: Accepted

#20 [17기 김채현] Add: ResumePartialView
  resume/tests.py
  resume/urls.py
  resume/views.py
  wantus/urls.py
Labels: Status: Accepted

#10 [17기 김채현] ResumeView (GET, POST, DELETE) + unittest (찐)
  resume/tests.py
  resume/urls.py
  resume/views.py
  utils.py
Labels: Status: Accepted

#15 [17기 장성준] PostingListView 생성, filtering 완료, unittest 완료, 통신 완료, 충돌 해결
  posting/tests.py
  posting/urls.py
  posting/views.py
  wantus/settings.py
Labels: Status: 리뷰 요청

#21 [17기 장성준] ApplyView 생성, unittest 완료
  apply/tests.py
  apply/urls.py
  apply/views.py
  wantus/urls.py
Labels: Status: 리뷰 요청

#17 [17기 강현수] S3 파일 삭제 로직 구현
  resume/tests.py
  resume/urls.py
  resume/views.py
Labels: Status: Accepted

#22 [17기 강현수] 디테일 페이지 수정
  posting/tests.py
  posting/views.py
Labels: Status: Accepted

#19 [17기 김채현] MyWantUsView (My원티드)
  apply/tests.py
  apply/urls.py
  apply/views.py
  requirements.txt
  resume/tests.py
  wantus/settings.py
Labels: Status: 리뷰 요청
